---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: LICENSE
name: netsim_iosxr
namespace: dataductus
description: Ansible Network Collection for Cisco IOSXR devices netsim.
readme: README.md
repository: https://github.com/merizrizal/cisco.iosxr
issues: https://github.com/ansible-collections/cisco.iosxr/issues
tags: [cisco, iosxr, netsim, networking, netconf]
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: "0.0.1"
